# Generated by Django 6.0.2 on 2026-03-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0003_add_task_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_comments/%Y/%m/', verbose_name='Прикреплённый файл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='WebSite.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to='WebSite.student')),
            ],
            options={
                'verbose_name': 'Комментарий к уроку',
                'verbose_name_plural': 'Комментарии к урокам',
                'ordering': ['-created_at'],
            },
        ),
    ]
