# Generated by Django 6.0.2 on 2026-03-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0005_notifications_and_news'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='WebSite_not_student_b729b7_idx',
            old_name='notif_student_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='WebSite_not_student_fdb7dc_idx',
            old_name='notif_student_lesson_kind_idx',
        ),
    ]
