# Generated by Django 6.0.2 on 2026-03-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0007_add_test_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='profile_id',
            field=models.CharField(blank=True, help_text='Выбранное направление профориентации (ai_business, design_content, python_ml, analytics) для сохранения в TestResult после верификации', max_length=32, null=True),
        ),
    ]
