# Generated by Django 6.0.2 on 2026-03-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0008_add_otp_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proftest_offer_shown_at',
            field=models.DateTimeField(blank=True, help_text='Когда впервые показали предложение пройти профтест в профиле (один раз при первом входе)', null=True),
        ),
    ]
