# Generated by Django 6.0.2 on 2026-03-05 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0009_add_proftest_offer_shown_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('telegram', models.CharField(help_text='Username или контакт', max_length=128, verbose_name='Telegram')),
                ('tag', models.CharField(blank=True, max_length=128, verbose_name='Тег / псевдоним')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('contacted', 'Связались'), ('paid', 'Оплачено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='WebSite.course')),
                ('student', models.ForeignKey(blank=True, help_text='Если пользователь был авторизован при подаче заявки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_applications', to='WebSite.student')),
            ],
            options={
                'verbose_name': 'Заявка на курс',
                'verbose_name_plural': 'Заявки на курсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
