# Generated by Django 6.0.2 on 2026-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0010_add_course_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Длительность курса в месяцах (например: 7)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='modules_description',
            field=models.TextField(blank=True, help_text='Краткое описание модулей по месяцам, например: 1 месяц — Python; 2 месяц — SQL; 3 месяц — Backend'),
        ),
        migrations.AddField(
            model_name='course',
            name='trailer_video_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео (YouTube и т.д.) — трейлер или обзор курса', max_length=500),
        ),
    ]
