# Generated by Django 6.0.2 on 2026-03-07 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0012_add_telegram_link_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mentor',
            field=models.ForeignKey(blank=True, help_text='Ментор группы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentoring_groups', to='WebSite.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Учитель курса в этой группе', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to='WebSite.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Кто создал урок (учитель/ментор)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to='WebSite.teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='study_groups', to='WebSite.student'),
        ),
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='WebSite.group')),
            ],
            options={
                'verbose_name': 'Сообщение чата группы',
                'verbose_name_plural': 'Сообщения чатов групп',
                'ordering': ['created_at'],
            },
        ),
    ]
