# Generated by Django 6.0.2 on 2026-03-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0013_add_group_teacher_mentor_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='learning_mode',
            field=models.CharField(choices=[('active', 'Активное (последовательно)'), ('smooth', 'Плавное')], default='smooth', help_text='Активное: следующий урок открывается после сдачи предыдущего и в назначенное время. Плавное: уроки открыты по расписанию.', max_length=20),
        ),
    ]
