# Generated by Django 6.0.2 on 2026-03-07 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0014_tariff_learning_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('lesson', 'Задание на уроке'), ('homework', 'Домашнее задание'), ('control', 'Контрольная работа')], default='lesson', help_text='Контрольные может проверять только учитель.', max_length=20, verbose_name='Тип задания'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='grade_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Балл'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда выставлена оценка'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Кто выставил оценку'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('news', 'Новость'), ('homework', 'Домашнее задание'), ('lesson_soon', 'Урок через 30 мин'), ('lesson_started', 'Урок начался'), ('chat_message', 'Сообщение в чате')], db_index=True, max_length=20),
        ),
    ]
